require:
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# Current state is that we prefer the opposite (reduce/inject)
Style/EachWithObject:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

# 80 is not contemporary anymore
Metrics/LineLength:
  Max: 120

# RSpec cops
RSpec/NestedGroups:
  Max: 3
