AllCops:
  Exclude:
    - Rakefile
    - ryodo.gemspec
    - checks/matching.rb

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
