rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
  - jruby-19mode
  - jruby-18mode
  - rbx-19mode
  - rbx-18mode
  - ruby-head
  - jruby-head

branches:
  only:
    - develop
    - master

notifications:
  email:
    - chris@dinarrr.com
