language: ruby
cache: bundler

rvm:
  - 2.4.0
  - 2.3.3

branches:
  only:
    - develop
    - master

env:
  global:
    - secure: "D3z4RvKc32obw+Tnd92VLwpGHca5HP3oMpCrMo1AbzsZcEpTuiIlQ+8byQt0MfnPABfJy/MNnXJNefVjZr7rOkGH6NiIAR2zH0Ajb0HJytXocG5a4KIYY6BJtavwdX4PLTbOHassdfxkuOrMkF0lVcxBPeGIFUYUytahnYDw9q0="
